# Sync Contracts Workflow - Auto-Healing
name: sync-contracts
description: "Automatically updates contracts based on drift findings in the sprint-audit report. Used by Kai (System Integrator)."
author: "NETECMT APC Engine"

# Critical variables from config
config_source: "{project-root}/_netecmt/core/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
reports_dir: "{project-root}/_netecmt/reports"
contracts_dir: "{project-root}/_netecmt/contracts"

# Workflow components
installed_path: "{project-root}/_netecmt/core/workflows/sync-contracts"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

# Inputs
variables:
  audit_report_path: "" # Required: path to the JSON report (e.g., _netecmt/reports/sprint-audit-xxx.json)
  execution_mode: "auto-healing"

# Smart input file references
input_file_patterns:
  audit_report:
    description: "The JSON report containing drift findings"
    whole: "{audit_report_path}"
    load_strategy: "FULL_LOAD"

standalone: true
